//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
//
//     Produced by Entity Framework Visual Editor v3.0.4.7
//     Source:                    https://github.com/msawczyn/EFDesigner
//     Visual Studio Marketplace: https://marketplace.visualstudio.com/items?itemName=michaelsawczyn.EFDesigner
//     Documentation:             https://msawczyn.github.io/EFDesigner/
//     License (MIT):             https://github.com/msawczyn/EFDesigner/blob/master/LICENSE
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DOS_DAL
{
   /// <inheritdoc/>
   public partial class DOSContext : DbContext
   {
      #region DbSets

      /// <summary>
      /// Repository for global::DOS_DAL.Models.ManufacturingStep - Model for ManufacturingStep,
      /// </summary>
      public virtual Microsoft.EntityFrameworkCore.DbSet<global::DOS_DAL.Models.ManufacturingStep> ManufacturingSteps { get; set; }

      /// <summary>
      /// Repository for global::DOS_DAL.Models.Order - Model for Order.
      /// </summary>
      public virtual Microsoft.EntityFrameworkCore.DbSet<global::DOS_DAL.Models.Order> Orders { get; set; }

      /// <summary>
      /// Repository for global::DOS_DAL.Models.Process - Model for Process.
      /// </summary>
      public virtual Microsoft.EntityFrameworkCore.DbSet<global::DOS_DAL.Models.Process> Processes { get; set; }

      /// <summary>
      /// Repository for global::DOS_DAL.Models.Product - Model for Product.
      /// </summary>
      public virtual Microsoft.EntityFrameworkCore.DbSet<global::DOS_DAL.Models.Product> Products { get; set; }

      /// <summary>
      /// Repository for global::DOS_DAL.Models.Role - Model for Role.
      /// </summary>
      public virtual Microsoft.EntityFrameworkCore.DbSet<global::DOS_DAL.Models.Role> Roles { get; set; }

      /// <summary>
      /// Repository for global::DOS_DAL.Models.Tolerance - Model for Tolerance.
      /// </summary>
      public virtual Microsoft.EntityFrameworkCore.DbSet<global::DOS_DAL.Models.Tolerance> Tolerances { get; set; }

      /// <summary>
      /// Repository for global::DOS_DAL.Models.User - Model for User.
      /// </summary>
      public virtual Microsoft.EntityFrameworkCore.DbSet<global::DOS_DAL.Models.User> Users { get; set; }

      #endregion DbSets

      /// <inheritdoc />
      public DOSContext(DbContextOptions<DOSContext> options) : base(options)
      {
      }

      partial void CustomInit(DbContextOptionsBuilder optionsBuilder);

      /// <inheritdoc />
      protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
      {
         optionsBuilder.UseLazyLoadingProxies();

         CustomInit(optionsBuilder);
      }

      partial void OnModelCreatingImpl(ModelBuilder modelBuilder);
      partial void OnModelCreatedImpl(ModelBuilder modelBuilder);

      /// <inheritdoc />
      protected override void OnModelCreating(ModelBuilder modelBuilder)
      {
         base.OnModelCreating(modelBuilder);
         OnModelCreatingImpl(modelBuilder);

         modelBuilder.HasDefaultSchema("dbo");

         modelBuilder.Entity<global::DOS_DAL.Models.ManufacturingStep>()
                     .ToTable("ManufacturingStep")
                     .HasKey(t => t.Id);
         modelBuilder.Entity<global::DOS_DAL.Models.ManufacturingStep>()
                     .Property(t => t.Id)
                     .ValueGeneratedOnAdd()
                     .IsRequired();
         modelBuilder.Entity<global::DOS_DAL.Models.ManufacturingStep>()
                     .Property(t => t.Wavelength)
                     .HasColumnType("decimal(8,4)")
                     .IsRequired()
                     .HasDefaultValue(0);
         modelBuilder.Entity<global::DOS_DAL.Models.ManufacturingStep>()
                     .Property(t => t.Intensity)
                     .HasColumnType("decimal(8,4)")
                     .IsRequired()
                     .HasDefaultValue(0);
         modelBuilder.Entity<global::DOS_DAL.Models.ManufacturingStep>()
                     .Property(t => t.Temperature)
                     .HasColumnType("decimal(8,4)")
                     .IsRequired()
                     .HasDefaultValue(0);
         modelBuilder.Entity<global::DOS_DAL.Models.ManufacturingStep>()
                     .Property(t => t.Humidity)
                     .HasColumnType("decimal(8,4)")
                     .IsRequired()
                     .HasDefaultValue(0);
         modelBuilder.Entity<global::DOS_DAL.Models.ManufacturingStep>()
                     .Property(t => t.Edited)
                     .IsRequired();
         modelBuilder.Entity<global::DOS_DAL.Models.ManufacturingStep>()
                     .HasOne<global::DOS_DAL.Models.User>(p => p.EditedBy)
                     .WithMany()
                     .HasForeignKey("EditedById")
                     .OnDelete(DeleteBehavior.NoAction);
         modelBuilder.Entity<global::DOS_DAL.Models.ManufacturingStep>()
                     .HasOne<global::DOS_DAL.Models.Process>(p => p.Process)
                     .WithMany()
                     .HasForeignKey("ProcessId")
                     .OnDelete(DeleteBehavior.NoAction);
         modelBuilder.Entity<global::DOS_DAL.Models.ManufacturingStep>().Navigation(e => e.Process).IsRequired();

         modelBuilder.Entity<global::DOS_DAL.Models.Order>()
                     .ToTable("Order")
                     .HasKey(t => t.Id);
         modelBuilder.Entity<global::DOS_DAL.Models.Order>()
                     .Property(t => t.Id)
                     .ValueGeneratedOnAdd()
                     .IsRequired();
         modelBuilder.Entity<global::DOS_DAL.Models.Order>()
                     .Property(t => t.Status)
                     .HasMaxLength(255)
                     .IsRequired();
         modelBuilder.Entity<global::DOS_DAL.Models.Order>()
                     .Property(t => t.SerialNumber)
                     .HasMaxLength(255)
                     .IsRequired();
         modelBuilder.Entity<global::DOS_DAL.Models.Order>().HasIndex(t => t.SerialNumber)
                     .IsUnique();
         modelBuilder.Entity<global::DOS_DAL.Models.Order>()
                     .Property(t => t.Customer)
                     .HasMaxLength(255)
                     .IsRequired();
         modelBuilder.Entity<global::DOS_DAL.Models.Order>()
                     .Property(t => t.Notes)
                     .HasMaxLength(1023);
         modelBuilder.Entity<global::DOS_DAL.Models.Order>()
                     .Property(t => t.Created)
                     .IsRequired();
         modelBuilder.Entity<global::DOS_DAL.Models.Order>()
                     .Property(t => t.Edited)
                     .IsRequired();
         modelBuilder.Entity<global::DOS_DAL.Models.Order>()
                     .Property(t => t.IsDeleted)
                     .IsRequired();
         modelBuilder.Entity<global::DOS_DAL.Models.Order>()
                     .HasOne<global::DOS_DAL.Models.User>(p => p.CreatedBy)
                     .WithMany()
                     .HasForeignKey("CreatedById")
                     .OnDelete(DeleteBehavior.NoAction);
         modelBuilder.Entity<global::DOS_DAL.Models.Order>()
                     .HasOne<global::DOS_DAL.Models.User>(p => p.EditedBy)
                     .WithMany()
                     .HasForeignKey("EditedById")
                     .OnDelete(DeleteBehavior.NoAction);
         modelBuilder.Entity<global::DOS_DAL.Models.Order>()
                     .HasOne<global::DOS_DAL.Models.Product>(p => p.Product)
                     .WithMany()
                     .HasForeignKey("ProductId")
                     .OnDelete(DeleteBehavior.NoAction);
         modelBuilder.Entity<global::DOS_DAL.Models.Order>().Navigation(e => e.Product).IsRequired();
         modelBuilder.Entity<global::DOS_DAL.Models.Order>()
                     .HasMany<global::DOS_DAL.Models.ManufacturingStep>(p => p.ManufacturingSteps)
                     .WithOne(p => p.Order)
                     .HasForeignKey("OrderId")
                     .OnDelete(DeleteBehavior.Cascade);
         modelBuilder.Entity<global::DOS_DAL.Models.ManufacturingStep>().Navigation(e => e.Order).IsRequired();

         modelBuilder.Entity<global::DOS_DAL.Models.Process>()
                     .ToTable("Process")
                     .HasKey(t => t.Id);
         modelBuilder.Entity<global::DOS_DAL.Models.Process>()
                     .Property(t => t.Id)
                     .ValueGeneratedOnAdd()
                     .IsRequired();
         modelBuilder.Entity<global::DOS_DAL.Models.Process>()
                     .Property(t => t.Name)
                     .HasMaxLength(255)
                     .IsRequired();
         modelBuilder.Entity<global::DOS_DAL.Models.Process>().HasIndex(t => t.Name)
                     .IsUnique();

         modelBuilder.Entity<global::DOS_DAL.Models.Product>()
                     .ToTable("Product")
                     .HasKey(t => t.Id);
         modelBuilder.Entity<global::DOS_DAL.Models.Product>()
                     .Property(t => t.Id)
                     .ValueGeneratedOnAdd()
                     .IsRequired();
         modelBuilder.Entity<global::DOS_DAL.Models.Product>()
                     .Property(t => t.Name)
                     .HasMaxLength(255)
                     .IsRequired();
         modelBuilder.Entity<global::DOS_DAL.Models.Product>().HasIndex(t => t.Name)
                     .IsUnique();
         modelBuilder.Entity<global::DOS_DAL.Models.Product>()
                     .Property(t => t.Description)
                     .HasMaxLength(1023);
         modelBuilder.Entity<global::DOS_DAL.Models.Product>()
                     .Property(t => t.IsDeleted)
                     .IsRequired();
         modelBuilder.Entity<global::DOS_DAL.Models.Product>()
                     .HasMany<global::DOS_DAL.Models.Process>(p => p.Processes)
                     .WithMany(p => p.Products)
                     .UsingEntity(x => x.ToTable("ProductProcess"));

         modelBuilder.Entity<global::DOS_DAL.Models.Role>()
                     .ToTable("Role")
                     .HasKey(t => t.Id);
         modelBuilder.Entity<global::DOS_DAL.Models.Role>()
                     .Property(t => t.Id)
                     .ValueGeneratedOnAdd()
                     .IsRequired();
         modelBuilder.Entity<global::DOS_DAL.Models.Role>()
                     .Property(t => t.Name)
                     .HasMaxLength(255)
                     .IsRequired();
         modelBuilder.Entity<global::DOS_DAL.Models.Role>().HasIndex(t => t.Name)
                     .IsUnique();

         modelBuilder.Entity<global::DOS_DAL.Models.Tolerance>()
                     .ToTable("Tolerance")
                     .HasKey(t => t.Id);
         modelBuilder.Entity<global::DOS_DAL.Models.Tolerance>()
                     .Property(t => t.Id)
                     .ValueGeneratedOnAdd()
                     .IsRequired();
         modelBuilder.Entity<global::DOS_DAL.Models.Tolerance>()
                     .Property(t => t.ValueName)
                     .HasMaxLength(255)
                     .IsRequired();
         modelBuilder.Entity<global::DOS_DAL.Models.Tolerance>()
                     .Property(t => t.MaxValue)
                     .HasColumnType("decimal(8,4)")
                     .IsRequired();
         modelBuilder.Entity<global::DOS_DAL.Models.Tolerance>()
                     .Property(t => t.MinValue)
                     .HasColumnType("decimal(8,4)")
                     .IsRequired();
         modelBuilder.Entity<global::DOS_DAL.Models.Tolerance>()
                     .Property(t => t.Edited)
                     .IsRequired();
         modelBuilder.Entity<global::DOS_DAL.Models.Tolerance>()
                     .HasOne<global::DOS_DAL.Models.User>(p => p.EditedBy)
                     .WithMany()
                     .HasForeignKey("EditedById")
                     .OnDelete(DeleteBehavior.NoAction);
         modelBuilder.Entity<global::DOS_DAL.Models.Tolerance>()
                     .HasOne<global::DOS_DAL.Models.Product>(p => p.Product)
                     .WithMany()
                     .HasForeignKey("ProductId")
                     .OnDelete(DeleteBehavior.NoAction);
         modelBuilder.Entity<global::DOS_DAL.Models.Tolerance>().Navigation(e => e.Product).IsRequired();
         modelBuilder.Entity<global::DOS_DAL.Models.Tolerance>()
                     .HasOne<global::DOS_DAL.Models.Process>(p => p.Process)
                     .WithMany()
                     .HasForeignKey("ProcessId")
                     .OnDelete(DeleteBehavior.NoAction);
         modelBuilder.Entity<global::DOS_DAL.Models.Tolerance>().Navigation(e => e.Process).IsRequired();

         modelBuilder.Entity<global::DOS_DAL.Models.User>()
                     .ToTable("User")
                     .HasKey(t => t.Id);
         modelBuilder.Entity<global::DOS_DAL.Models.User>()
                     .Property(t => t.Id)
                     .ValueGeneratedOnAdd()
                     .IsRequired();
         modelBuilder.Entity<global::DOS_DAL.Models.User>()
                     .Property(t => t.Username)
                     .HasMaxLength(255)
                     .IsRequired();
         modelBuilder.Entity<global::DOS_DAL.Models.User>().HasIndex(t => t.Username)
                     .IsUnique();
         modelBuilder.Entity<global::DOS_DAL.Models.User>()
                     .Property(t => t.Password)
                     .HasMaxLength(255)
                     .IsRequired();
         modelBuilder.Entity<global::DOS_DAL.Models.User>()
                     .Property(t => t.FirstName)
                     .HasMaxLength(255);
         modelBuilder.Entity<global::DOS_DAL.Models.User>()
                     .Property(t => t.LastName)
                     .HasMaxLength(255);
         modelBuilder.Entity<global::DOS_DAL.Models.User>()
                     .Property(t => t.Email)
                     .HasMaxLength(255);
         modelBuilder.Entity<global::DOS_DAL.Models.User>()
                     .HasOne<global::DOS_DAL.Models.Role>(p => p.Role)
                     .WithMany()
                     .HasForeignKey("RoleId")
                     .OnDelete(DeleteBehavior.NoAction);
         modelBuilder.Entity<global::DOS_DAL.Models.User>().Navigation(e => e.Role).IsRequired();

         OnModelCreatedImpl(modelBuilder);
      }
   }
}
