//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
//
//     Produced by Entity Framework Visual Editor v3.0.4.7
//     Source:                    https://github.com/msawczyn/EFDesigner
//     Visual Studio Marketplace: https://marketplace.visualstudio.com/items?itemName=michaelsawczyn.EFDesigner
//     Documentation:             https://msawczyn.github.io/EFDesigner/
//     License (MIT):             https://github.com/msawczyn/EFDesigner/blob/master/LICENSE
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Runtime.CompilerServices;

namespace DOS_DAL.Models
{
   /// <summary>
   /// Model for ManufacturingStep,
   /// </summary>
   [System.ComponentModel.Description("Model for ManufacturingStep,")]
   public partial class ManufacturingStep: DOS_DAL.Interfaces.IBaseModel, DOS_DAL.Interfaces.ITrackEdit
   {
      partial void Init();

      /// <summary>
      /// Default constructor
      /// </summary>
      public ManufacturingStep()
      {
         Wavelength = 0;
         Intensity = 0;
         Temperature = 0;
         Humidity = 0;

         Init();
      }

      /// <summary>
      /// Public constructor with required data
      /// </summary>
      /// <param name="wavelength">Wavelength value.</param>
      /// <param name="intensity">Intensity value.</param>
      /// <param name="temperature">Temperature value.</param>
      /// <param name="humidity">Humidity value.</param>
      /// <param name="edited">When was ManufacturingStep last Edited.</param>
      /// <param name="process">Process FK</param>
      /// <param name="order">Order FK</param>
      public ManufacturingStep(DateTime edited, global::DOS_DAL.Models.Process process, global::DOS_DAL.Models.Order order, decimal wavelength = 0m, decimal intensity = 0m, decimal temperature = 0m, decimal humidity = 0m)
      {
         this.Wavelength = wavelength;

         this.Intensity = intensity;

         this.Temperature = temperature;

         this.Humidity = humidity;

         this.Edited = edited;

         if (process == null) throw new ArgumentNullException(nameof(process));
         this.Process = process;

         if (order == null) throw new ArgumentNullException(nameof(order));
         this.Order = order;
         order.ManufacturingSteps.Add(this);

         Init();
      }

      /// <summary>
      /// Static create function (for use in LINQ queries, etc.)
      /// </summary>
      /// <param name="wavelength">Wavelength value.</param>
      /// <param name="intensity">Intensity value.</param>
      /// <param name="temperature">Temperature value.</param>
      /// <param name="humidity">Humidity value.</param>
      /// <param name="edited">When was ManufacturingStep last Edited.</param>
      /// <param name="process">Process FK</param>
      /// <param name="order">Order FK</param>
      public static ManufacturingStep Create(DateTime edited, global::DOS_DAL.Models.Process process, global::DOS_DAL.Models.Order order, decimal wavelength = 0m, decimal intensity = 0m, decimal temperature = 0m, decimal humidity = 0m)
      {
         return new ManufacturingStep(edited, process, order, wavelength, intensity, temperature, humidity);
      }

      /*************************************************************************
       * Properties
       *************************************************************************/

      /// <summary>
      /// Identity, Indexed, Required
      /// Unique identifier
      /// </summary>
      [Key]
      [Required]
      [System.ComponentModel.Description("Unique identifier")]
      public int Id { get; set; }

      /// <summary>
      /// Backing field for Wavelength
      /// </summary>
      protected decimal _wavelength;
      /// <summary>
      /// When provided in a partial class, allows value of Wavelength to be changed before setting.
      /// </summary>
      partial void SetWavelength(decimal oldValue, ref decimal newValue);
      /// <summary>
      /// When provided in a partial class, allows value of Wavelength to be changed before returning.
      /// </summary>
      partial void GetWavelength(ref decimal result);

      /// <summary>
      /// Required, Default value = 0
      /// Wavelength value.
      /// </summary>
      [Required]
      [System.ComponentModel.Description("Wavelength value.")]
      public decimal Wavelength
      {
         get
         {
            decimal value = _wavelength;
            GetWavelength(ref value);
            return (_wavelength = value);
         }
         set
         {
            decimal oldValue = _wavelength;
            SetWavelength(oldValue, ref value);
            if (oldValue != value)
            {
               _wavelength = value;
               OnPropertyChanged();
            }
         }
      }

      /// <summary>
      /// Backing field for Intensity
      /// </summary>
      protected decimal _intensity;
      /// <summary>
      /// When provided in a partial class, allows value of Intensity to be changed before setting.
      /// </summary>
      partial void SetIntensity(decimal oldValue, ref decimal newValue);
      /// <summary>
      /// When provided in a partial class, allows value of Intensity to be changed before returning.
      /// </summary>
      partial void GetIntensity(ref decimal result);

      /// <summary>
      /// Required, Default value = 0
      /// Intensity value.
      /// </summary>
      [Required]
      [System.ComponentModel.Description("Intensity value.")]
      public decimal Intensity
      {
         get
         {
            decimal value = _intensity;
            GetIntensity(ref value);
            return (_intensity = value);
         }
         set
         {
            decimal oldValue = _intensity;
            SetIntensity(oldValue, ref value);
            if (oldValue != value)
            {
               _intensity = value;
               OnPropertyChanged();
            }
         }
      }

      /// <summary>
      /// Backing field for Temperature
      /// </summary>
      protected decimal _temperature;
      /// <summary>
      /// When provided in a partial class, allows value of Temperature to be changed before setting.
      /// </summary>
      partial void SetTemperature(decimal oldValue, ref decimal newValue);
      /// <summary>
      /// When provided in a partial class, allows value of Temperature to be changed before returning.
      /// </summary>
      partial void GetTemperature(ref decimal result);

      /// <summary>
      /// Required, Default value = 0
      /// Temperature value.
      /// </summary>
      [Required]
      [System.ComponentModel.Description("Temperature value.")]
      public decimal Temperature
      {
         get
         {
            decimal value = _temperature;
            GetTemperature(ref value);
            return (_temperature = value);
         }
         set
         {
            decimal oldValue = _temperature;
            SetTemperature(oldValue, ref value);
            if (oldValue != value)
            {
               _temperature = value;
               OnPropertyChanged();
            }
         }
      }

      /// <summary>
      /// Backing field for Humidity
      /// </summary>
      protected decimal _humidity;
      /// <summary>
      /// When provided in a partial class, allows value of Humidity to be changed before setting.
      /// </summary>
      partial void SetHumidity(decimal oldValue, ref decimal newValue);
      /// <summary>
      /// When provided in a partial class, allows value of Humidity to be changed before returning.
      /// </summary>
      partial void GetHumidity(ref decimal result);

      /// <summary>
      /// Required, Default value = 0
      /// Humidity value.
      /// </summary>
      [Required]
      [System.ComponentModel.Description("Humidity value.")]
      public decimal Humidity
      {
         get
         {
            decimal value = _humidity;
            GetHumidity(ref value);
            return (_humidity = value);
         }
         set
         {
            decimal oldValue = _humidity;
            SetHumidity(oldValue, ref value);
            if (oldValue != value)
            {
               _humidity = value;
               OnPropertyChanged();
            }
         }
      }

      /// <summary>
      /// Backing field for Edited
      /// </summary>
      protected DateTime _edited;
      /// <summary>
      /// When provided in a partial class, allows value of Edited to be changed before setting.
      /// </summary>
      partial void SetEdited(DateTime oldValue, ref DateTime newValue);
      /// <summary>
      /// When provided in a partial class, allows value of Edited to be changed before returning.
      /// </summary>
      partial void GetEdited(ref DateTime result);

      /// <summary>
      /// Required
      /// When was ManufacturingStep last Edited.
      /// </summary>
      [Required]
      [System.ComponentModel.Description("When was ManufacturingStep last Edited.")]
      public DateTime Edited
      {
         get
         {
            DateTime value = _edited;
            GetEdited(ref value);
            return (_edited = value);
         }
         set
         {
            DateTime oldValue = _edited;
            SetEdited(oldValue, ref value);
            if (oldValue != value)
            {
               _edited = value;
               OnPropertyChanged();
            }
         }
      }

      /*************************************************************************
       * Navigation properties
       *************************************************************************/

      /// <summary>
      /// User FK
      /// </summary>
      [Description("User FK")]
      public virtual global::DOS_DAL.Models.User EditedBy { get; set; }

      /// <summary>
      /// Required&lt;br/&gt;
      /// Process FK
      /// </summary>
      [Description("Process FK")]
      public virtual global::DOS_DAL.Models.Process Process { get; set; }

      /// <summary>
      /// Required&lt;br/&gt;
      /// Order FK
      /// </summary>
      [Description("Order FK")]
      public virtual global::DOS_DAL.Models.Order Order { get; set; }

   }
}

