//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
//
//     Produced by Entity Framework Visual Editor v3.0.4.7
//     Source:                    https://github.com/msawczyn/EFDesigner
//     Visual Studio Marketplace: https://marketplace.visualstudio.com/items?itemName=michaelsawczyn.EFDesigner
//     Documentation:             https://msawczyn.github.io/EFDesigner/
//     License (MIT):             https://github.com/msawczyn/EFDesigner/blob/master/LICENSE
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Runtime.CompilerServices;

namespace DOS_DAL
{
   /// <summary>
   /// Model for User.
   /// </summary>
   [System.ComponentModel.Description("Model for User.")]
   public partial class User
   {
      partial void Init();

      /// <summary>
      /// Default constructor. Protected due to required properties, but present because EF needs it.
      /// </summary>
      protected User()
      {
         Init();
      }

      /// <summary>
      /// Replaces default constructor, since it's protected. Caller assumes responsibility for setting all required values before saving.
      /// </summary>
      public static User CreateUserUnsafe()
      {
         return new User();
      }

      /// <summary>
      /// Public constructor with required data
      /// </summary>
      /// <param name="username">Username of User.</param>
      /// <param name="password">Password of User.</param>
      /// <param name="role">Role FK</param>
      public User(string username, string password, global::DOS_DAL.Role role)
      {
         if (string.IsNullOrEmpty(username)) throw new ArgumentNullException(nameof(username));
         this.Username = username;

         if (string.IsNullOrEmpty(password)) throw new ArgumentNullException(nameof(password));
         this.Password = password;

         if (role == null) throw new ArgumentNullException(nameof(role));
         this.Role = role;

         Init();
      }

      /// <summary>
      /// Static create function (for use in LINQ queries, etc.)
      /// </summary>
      /// <param name="username">Username of User.</param>
      /// <param name="password">Password of User.</param>
      /// <param name="role">Role FK</param>
      public static User Create(string username, string password, global::DOS_DAL.Role role)
      {
         return new User(username, password, role);
      }

      /*************************************************************************
       * Properties
       *************************************************************************/

      /// <summary>
      /// Identity, Indexed, Required
      /// Unique identifier
      /// </summary>
      [Key]
      [Required]
      [System.ComponentModel.Description("Unique identifier")]
      public int Id { get; set; }

      /// <summary>
      /// Indexed, Required, Max length = 255
      /// Username of User.
      /// </summary>
      [Required]
      [MaxLength(255)]
      [StringLength(255)]
      [System.ComponentModel.Description("Username of User.")]
      public string Username { get; set; }

      /// <summary>
      /// Required, Max length = 255
      /// Password of User.
      /// </summary>
      [Required]
      [MaxLength(255)]
      [StringLength(255)]
      [System.ComponentModel.Description("Password of User.")]
      public string Password { get; set; }

      /// <summary>
      /// Max length = 255
      /// FirstName of User.
      /// </summary>
      [MaxLength(255)]
      [StringLength(255)]
      [System.ComponentModel.Description("FirstName of User.")]
      public string FirstName { get; set; }

      /// <summary>
      /// Max length = 255
      /// LastName of User.
      /// </summary>
      [MaxLength(255)]
      [StringLength(255)]
      [System.ComponentModel.Description("LastName of User.")]
      public string LastName { get; set; }

      /// <summary>
      /// Max length = 255
      /// Email of User.
      /// </summary>
      [MaxLength(255)]
      [StringLength(255)]
      [System.ComponentModel.Description("Email of User.")]
      public string Email { get; set; }

      /*************************************************************************
       * Navigation properties
       *************************************************************************/

      /// <summary>
      /// Required&lt;br/&gt;
      /// Role FK
      /// </summary>
      [Description("Role FK")]
      public virtual global::DOS_DAL.Role Role { get; set; }

   }
}

